---
- name: Add Repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ ansible_lsb.id | lower }} {{ ansible_lsb.codename }} stable"
    state: present
  register: docker_repo

- name: Update repository list
  ansible.builtin.apt:
    update_cache: yes
