---
- hosts: all
  become: yes
  vars_files: 
  - "vars/packages_{{ ansible_os_family | lower }}.yml"

  roles:
    - golang
    - docker
    - docker-compose
    - update-environment
    - soak-tools
