---
- name: Add Repository
  ansible.builtin.yum_repository:
    description: Docker ce repository
    name: "docker-ce"
    baseurl: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/docker-ce.repo"
    state: present
  register: add_repo
